import type { Skill } from "./types";

export const BUILTIN_TAXONOMY: Skill[] = [
  // ───────── Programming Languages ─────────
  { id: "javascript", label: "JavaScript", category: "programming", aliases: ["JS", "ECMAScript", "ES6", "ES2020"] },
  { id: "typescript", label: "TypeScript", category: "programming", aliases: ["TS"] },
  { id: "python", label: "Python", category: "programming", aliases: ["Py", "Python3", "Python 3"] },
  { id: "java", label: "Java", category: "programming" },
  { id: "kotlin", label: "Kotlin", category: "programming" },
  { id: "scala", label: "Scala", category: "programming" },
  { id: "groovy", label: "Groovy", category: "programming" },
  { id: "csharp", label: "C#", category: "programming", aliases: ["C-Sharp", "CSharp", "dotnet C#"] },
  { id: "cpp", label: "C++", category: "programming", aliases: ["CPP"] },
  { id: "c", label: "C", category: "programming", matchTerms: ["C-Programmierung", "ANSI C", "C-Sprache", "Programmiersprache C"] },
  { id: "go", label: "Go", category: "programming", matchTerms: ["Golang", "Go-Lang"] },
  { id: "rust", label: "Rust", category: "programming" },
  { id: "ruby", label: "Ruby", category: "programming" },
  { id: "php", label: "PHP", category: "programming" },
  { id: "swift", label: "Swift", category: "programming", matchTerms: ["Swift", "SwiftUI"], caseSensitive: true },
  { id: "objc", label: "Objective-C", category: "programming", aliases: ["ObjC"] },
  { id: "dart", label: "Dart", category: "programming" },
  { id: "elixir", label: "Elixir", category: "programming" },
  { id: "erlang", label: "Erlang", category: "programming" },
  { id: "haskell", label: "Haskell", category: "programming" },
  { id: "clojure", label: "Clojure", category: "programming" },
  { id: "fsharp", label: "F#", category: "programming", aliases: ["FSharp"] },
  { id: "ocaml", label: "OCaml", category: "programming" },
  { id: "lua", label: "Lua", category: "programming" },
  { id: "perl", label: "Perl", category: "programming" },
  { id: "r-lang", label: "R", category: "programming", matchTerms: ["R-Sprache", "RStudio", "R Studio", "tidyverse", "ggplot2", "dplyr"] },
  { id: "matlab", label: "MATLAB", category: "programming" },
  { id: "sql", label: "SQL", category: "programming", aliases: ["ANSI SQL"] },
  { id: "tsql", label: "T-SQL", category: "programming", aliases: ["Transact-SQL"] },
  { id: "plsql", label: "PL/SQL", category: "programming", aliases: ["PLSQL"] },
  { id: "abap", label: "ABAP", category: "programming", aliases: ["ABAP OO", "ABAP Objects", "ABAP Cloud"] },
  { id: "cds", label: "ABAP CDS", category: "programming", aliases: ["Core Data Services", "CDS Views"] },
  { id: "cobol", label: "COBOL", category: "programming" },
  { id: "fortran", label: "Fortran", category: "programming" },
  { id: "assembly", label: "Assembly", category: "programming", aliases: ["ASM"] },
  { id: "bash", label: "Bash", category: "programming", aliases: ["Shell-Scripting", "Shell Scripting"] },
  { id: "powershell", label: "PowerShell", category: "programming" },
  { id: "vba", label: "VBA", category: "programming", aliases: ["Visual Basic for Applications"] },
  { id: "vbnet", label: "VB.NET", category: "programming", aliases: ["Visual Basic .NET"] },
  { id: "solidity", label: "Solidity", category: "programming" },
  { id: "html", label: "HTML", category: "programming", aliases: ["HTML5"] },
  { id: "css", label: "CSS", category: "programming", aliases: ["CSS3"] },
  { id: "sass", label: "Sass", category: "programming", aliases: ["SCSS"] },
  { id: "less", label: "LESS", category: "programming", caseSensitive: true },

  // ───────── Frameworks / Libraries ─────────
  { id: "react", label: "React", category: "framework", aliases: ["React.js", "ReactJS"] },
  { id: "nextjs", label: "Next.js", category: "framework", aliases: ["NextJS", "Next.JS"] },
  { id: "vue", label: "Vue", category: "framework", aliases: ["Vue.js", "VueJS"] },
  { id: "nuxt", label: "Nuxt", category: "framework", aliases: ["Nuxt.js"] },
  { id: "angular", label: "Angular", category: "framework", aliases: ["AngularJS", "Angular 2+"] },
  { id: "svelte", label: "Svelte", category: "framework" },
  { id: "sveltekit", label: "SvelteKit", category: "framework" },
  { id: "solid", label: "SolidJS", category: "framework", aliases: ["Solid.js"] },
  { id: "qwik", label: "Qwik", category: "framework" },
  { id: "remix", label: "Remix", category: "framework" },
  { id: "astro", label: "Astro", category: "framework" },
  { id: "gatsby", label: "Gatsby", category: "framework" },
  { id: "preact", label: "Preact", category: "framework" },
  { id: "lit", label: "Lit", category: "framework" },
  { id: "alpinejs", label: "Alpine.js", category: "framework" },
  { id: "htmx", label: "htmx", category: "framework" },
  { id: "jquery", label: "jQuery", category: "framework" },
  { id: "backbone", label: "Backbone.js", category: "framework" },
  { id: "ember", label: "Ember.js", category: "framework" },
  { id: "redux", label: "Redux", category: "framework" },
  { id: "mobx", label: "MobX", category: "framework" },
  { id: "zustand", label: "Zustand", category: "framework" },
  { id: "recoil", label: "Recoil", category: "framework" },
  { id: "jotai", label: "Jotai", category: "framework" },
  { id: "pinia", label: "Pinia", category: "framework" },
  { id: "vuex", label: "Vuex", category: "framework" },
  { id: "react-query", label: "TanStack Query", category: "framework", aliases: ["React Query"] },
  { id: "swr", label: "SWR", category: "framework" },
  { id: "apollo", label: "Apollo Client", category: "framework", aliases: ["Apollo GraphQL"] },
  { id: "relay", label: "Relay", category: "framework" },
  { id: "tailwind", label: "Tailwind CSS", category: "framework", aliases: ["TailwindCSS", "Tailwind"] },
  { id: "bootstrap", label: "Bootstrap", category: "framework" },
  { id: "mui", label: "Material UI", category: "framework", aliases: ["MUI", "Material-UI"] },
  { id: "chakra", label: "Chakra UI", category: "framework" },
  { id: "antd", label: "Ant Design", category: "framework", aliases: ["AntD"] },
  { id: "bulma", label: "Bulma", category: "framework" },
  { id: "shadcn", label: "shadcn/ui", category: "framework", aliases: ["Shadcn UI"] },
  { id: "express", label: "Express", category: "framework", matchTerms: ["Express.js", "ExpressJS", "Express Framework", "Express"], caseSensitive: true },
  { id: "fastify", label: "Fastify", category: "framework" },
  { id: "nestjs", label: "NestJS", category: "framework", aliases: ["Nest.js"] },
  { id: "koa", label: "Koa", category: "framework" },
  { id: "hapi", label: "Hapi", category: "framework" },
  { id: "django", label: "Django", category: "framework" },
  { id: "flask", label: "Flask", category: "framework" },
  { id: "fastapi", label: "FastAPI", category: "framework" },
  { id: "tornado", label: "Tornado", category: "framework" },
  { id: "spring", label: "Spring", category: "framework", aliases: ["Spring Framework"], caseSensitive: true },
  { id: "springboot", label: "Spring Boot", category: "framework", aliases: ["SpringBoot"] },
  { id: "quarkus", label: "Quarkus", category: "framework" },
  { id: "micronaut", label: "Micronaut", category: "framework" },
  { id: "laravel", label: "Laravel", category: "framework" },
  { id: "symfony", label: "Symfony", category: "framework" },
  { id: "rails", label: "Ruby on Rails", category: "framework", aliases: ["Rails", "RoR"] },
  { id: "aspnet", label: "ASP.NET", category: "framework", aliases: ["ASP.NET Core"] },
  { id: "dotnet", label: "ASP.NET MVC", category: "framework", aliases: [".NET MVC"] },
  { id: "dotnet-core", label: ".NET", category: "framework", aliases: [".NET Core", ".NET 6", ".NET 7", ".NET 8", "dotnet"] },
  { id: "blazor", label: "Blazor", category: "framework" },
  { id: "phoenix", label: "Phoenix", category: "framework", aliases: ["Phoenix Framework"] },
  { id: "rn", label: "React Native", category: "framework" },
  { id: "flutter", label: "Flutter", category: "framework" },
  { id: "ionic", label: "Ionic", category: "framework" },
  { id: "electron", label: "Electron", category: "framework" },
  { id: "tauri", label: "Tauri", category: "framework" },
  { id: "nodejs", label: "Node.js", category: "framework", aliases: ["NodeJS", "Node.JS"] },
  { id: "deno", label: "Deno", category: "framework" },
  { id: "bun", label: "Bun", category: "framework" },
  { id: "graphql", label: "GraphQL", category: "framework" },
  { id: "trpc", label: "tRPC", category: "framework" },
  { id: "prisma", label: "Prisma", category: "framework" },
  { id: "drizzle", label: "Drizzle ORM", category: "framework", aliases: ["DrizzleORM"] },
  { id: "typeorm", label: "TypeORM", category: "framework" },
  { id: "sequelize", label: "Sequelize", category: "framework" },
  { id: "hibernate", label: "Hibernate", category: "framework" },
  { id: "jpa", label: "JPA", category: "framework", aliases: ["Java Persistence API"] },
  { id: "mybatis", label: "MyBatis", category: "framework" },
  { id: "entityframework", label: "Entity Framework", category: "framework", aliases: ["EF Core"] },
  { id: "pandas", label: "pandas", category: "framework" },
  { id: "numpy", label: "NumPy", category: "framework" },
  { id: "scikit", label: "scikit-learn", category: "framework", aliases: ["sklearn"] },
  { id: "tensorflow", label: "TensorFlow", category: "framework" },
  { id: "pytorch", label: "PyTorch", category: "framework" },
  { id: "keras", label: "Keras", category: "framework" },
  { id: "huggingface", label: "Hugging Face", category: "framework", aliases: ["HuggingFace", "Transformers"] },
  { id: "langchain", label: "LangChain", category: "framework" },
  { id: "llamaindex", label: "LlamaIndex", category: "framework" },
  { id: "openai-sdk", label: "OpenAI SDK", category: "framework" },
  { id: "anthropic-sdk", label: "Anthropic SDK", category: "framework", aliases: ["Claude SDK"] },

  // ───────── Cloud / DevOps ─────────
  { id: "aws", label: "AWS", category: "cloud-devops", aliases: ["Amazon Web Services"] },
  { id: "azure", label: "Microsoft Azure", category: "cloud-devops", aliases: ["Azure"] },
  { id: "gcp", label: "Google Cloud Platform", category: "cloud-devops", aliases: ["GCP", "Google Cloud"] },
  { id: "vercel", label: "Vercel", category: "cloud-devops" },
  { id: "netlify", label: "Netlify", category: "cloud-devops" },
  { id: "cloudflare", label: "Cloudflare", category: "cloud-devops" },
  { id: "heroku", label: "Heroku", category: "cloud-devops" },
  { id: "digitalocean", label: "DigitalOcean", category: "cloud-devops" },
  { id: "ibm-cloud", label: "IBM Cloud", category: "cloud-devops" },
  { id: "oracle-cloud", label: "Oracle Cloud", category: "cloud-devops", aliases: ["OCI"] },
  { id: "alibaba-cloud", label: "Alibaba Cloud", category: "cloud-devops" },
  { id: "sap-btp", label: "SAP BTP", category: "cloud-devops", aliases: ["SAP Business Technology Platform"] },
  { id: "supabase", label: "Supabase", category: "cloud-devops" },
  { id: "firebase", label: "Firebase", category: "cloud-devops" },
  { id: "docker", label: "Docker", category: "cloud-devops" },
  { id: "podman", label: "Podman", category: "cloud-devops" },
  { id: "kubernetes", label: "Kubernetes", category: "cloud-devops", aliases: ["K8s", "K8S"] },
  { id: "helm", label: "Helm", category: "cloud-devops" },
  { id: "istio", label: "Istio", category: "cloud-devops" },
  { id: "linkerd", label: "Linkerd", category: "cloud-devops" },
  { id: "consul", label: "Consul", category: "cloud-devops" },
  { id: "vault", label: "HashiCorp Vault", category: "cloud-devops", aliases: ["Vault"] },
  { id: "terraform", label: "Terraform", category: "cloud-devops" },
  { id: "pulumi", label: "Pulumi", category: "cloud-devops" },
  { id: "cloudformation", label: "CloudFormation", category: "cloud-devops" },
  { id: "cdk", label: "AWS CDK", category: "cloud-devops" },
  { id: "ansible", label: "Ansible", category: "cloud-devops" },
  { id: "chef", label: "Chef", category: "cloud-devops" },
  { id: "puppet", label: "Puppet", category: "cloud-devops" },
  { id: "saltstack", label: "SaltStack", category: "cloud-devops" },
  { id: "jenkins", label: "Jenkins", category: "cloud-devops" },
  { id: "gitlab-ci", label: "GitLab CI/CD", category: "cloud-devops", aliases: ["GitLab CI", "GitLab Pipelines"] },
  { id: "github-actions", label: "GitHub Actions", category: "cloud-devops" },
  { id: "circleci", label: "CircleCI", category: "cloud-devops" },
  { id: "travisci", label: "Travis CI", category: "cloud-devops" },
  { id: "teamcity", label: "TeamCity", category: "cloud-devops" },
  { id: "bamboo", label: "Bamboo", category: "cloud-devops" },
  { id: "argo", label: "Argo Workflows", category: "cloud-devops" },
  { id: "argocd", label: "ArgoCD", category: "cloud-devops" },
  { id: "flux", label: "Flux CD", category: "cloud-devops", aliases: ["FluxCD"] },
  { id: "spinnaker", label: "Spinnaker", category: "cloud-devops" },
  { id: "tekton", label: "Tekton", category: "cloud-devops" },
  { id: "nginx", label: "Nginx", category: "cloud-devops" },
  { id: "apache", label: "Apache HTTP", category: "cloud-devops", aliases: ["Apache HTTPD"] },
  { id: "traefik", label: "Traefik", category: "cloud-devops" },
  { id: "haproxy", label: "HAProxy", category: "cloud-devops" },
  { id: "linux", label: "Linux", category: "cloud-devops", aliases: ["GNU/Linux"] },
  { id: "ubuntu", label: "Ubuntu", category: "cloud-devops" },
  { id: "debian", label: "Debian", category: "cloud-devops" },
  { id: "rhel", label: "Red Hat Enterprise Linux", category: "cloud-devops", aliases: ["RHEL"] },
  { id: "centos", label: "CentOS", category: "cloud-devops" },
  { id: "alpine", label: "Alpine Linux", category: "cloud-devops" },
  { id: "macos", label: "macOS", category: "cloud-devops", aliases: ["Mac OS"] },
  { id: "windows-server", label: "Windows Server", category: "cloud-devops" },
  { id: "lambda", label: "AWS Lambda", category: "cloud-devops" },
  { id: "ecs", label: "Amazon ECS", category: "cloud-devops", aliases: ["AWS ECS"] },
  { id: "eks", label: "Amazon EKS", category: "cloud-devops", aliases: ["AWS EKS"] },
  { id: "fargate", label: "AWS Fargate", category: "cloud-devops" },
  { id: "s3", label: "Amazon S3", category: "cloud-devops" },
  { id: "ec2", label: "Amazon EC2", category: "cloud-devops" },
  { id: "rds", label: "Amazon RDS", category: "cloud-devops" },
  { id: "cloudwatch", label: "CloudWatch", category: "cloud-devops" },
  { id: "cloudfront", label: "CloudFront", category: "cloud-devops" },
  { id: "route53", label: "Route 53", category: "cloud-devops" },
  { id: "sagemaker", label: "SageMaker", category: "cloud-devops" },
  { id: "redshift", label: "Amazon Redshift", category: "cloud-devops" },
  { id: "athena", label: "Amazon Athena", category: "cloud-devops" },
  { id: "glue", label: "AWS Glue", category: "cloud-devops" },
  { id: "step-functions", label: "AWS Step Functions", category: "cloud-devops" },
  { id: "azure-functions", label: "Azure Functions", category: "cloud-devops" },
  { id: "azure-devops", label: "Azure DevOps", category: "cloud-devops" },
  { id: "aks", label: "Azure Kubernetes Service", category: "cloud-devops", aliases: ["AKS"] },
  { id: "gke", label: "Google Kubernetes Engine", category: "cloud-devops", aliases: ["GKE"] },
  { id: "cloudrun", label: "Cloud Run", category: "cloud-devops" },
  { id: "cloudfunctions", label: "Cloud Functions", category: "cloud-devops" },

  // ───────── Databases ─────────
  { id: "postgres", label: "PostgreSQL", category: "database", aliases: ["Postgres"] },
  { id: "mysql", label: "MySQL", category: "database" },
  { id: "mariadb", label: "MariaDB", category: "database" },
  { id: "sqlite", label: "SQLite", category: "database" },
  { id: "oracle-db", label: "Oracle Database", category: "database", aliases: ["Oracle DB"] },
  { id: "mssql", label: "Microsoft SQL Server", category: "database", aliases: ["MS SQL", "MSSQL", "SQL Server"] },
  { id: "db2", label: "IBM Db2", category: "database", aliases: ["DB2"] },
  { id: "sap-hana", label: "SAP HANA", category: "database", aliases: ["HANA"] },
  { id: "mongodb", label: "MongoDB", category: "database", aliases: ["Mongo"] },
  { id: "couchdb", label: "CouchDB", category: "database" },
  { id: "couchbase", label: "Couchbase", category: "database" },
  { id: "cassandra", label: "Cassandra", category: "database" },
  { id: "redis", label: "Redis", category: "database" },
  { id: "memcached", label: "Memcached", category: "database" },
  { id: "elasticsearch", label: "Elasticsearch", category: "database", aliases: ["ElasticSearch"] },
  { id: "opensearch", label: "OpenSearch", category: "database" },
  { id: "solr", label: "Apache Solr", category: "database", aliases: ["Solr"] },
  { id: "neo4j", label: "Neo4j", category: "database" },
  { id: "arangodb", label: "ArangoDB", category: "database" },
  { id: "dynamodb", label: "DynamoDB", category: "database" },
  { id: "cosmosdb", label: "Cosmos DB", category: "database", aliases: ["Azure Cosmos DB"] },
  { id: "bigquery", label: "BigQuery", category: "database" },
  { id: "snowflake", label: "Snowflake", category: "database" },
  { id: "clickhouse", label: "ClickHouse", category: "database" },
  { id: "duckdb", label: "DuckDB", category: "database" },
  { id: "influxdb", label: "InfluxDB", category: "database" },
  { id: "timescaledb", label: "TimescaleDB", category: "database" },
  { id: "druid", label: "Apache Druid", category: "database" },
  { id: "pinot", label: "Apache Pinot", category: "database" },
  { id: "kafka", label: "Apache Kafka", category: "database", aliases: ["Kafka"] },
  { id: "pulsar", label: "Apache Pulsar", category: "database", aliases: ["Pulsar"] },
  { id: "rabbitmq", label: "RabbitMQ", category: "database" },
  { id: "activemq", label: "ActiveMQ", category: "database" },
  { id: "nats", label: "NATS", category: "database" },
  { id: "kinesis", label: "Amazon Kinesis", category: "database" },
  { id: "eventhub", label: "Azure Event Hubs", category: "database" },
  { id: "pubsub", label: "Google Pub/Sub", category: "database" },

  // ───────── Tools / Platforms ─────────
  { id: "git", label: "Git", category: "tool" },
  { id: "github", label: "GitHub", category: "tool" },
  { id: "gitlab", label: "GitLab", category: "tool" },
  { id: "bitbucket", label: "Bitbucket", category: "tool" },
  { id: "svn", label: "Subversion", category: "tool", aliases: ["SVN"] },
  { id: "mercurial", label: "Mercurial", category: "tool", aliases: ["Hg"] },
  { id: "jira", label: "Jira", category: "tool" },
  { id: "confluence", label: "Confluence", category: "tool" },
  { id: "slack", label: "Slack", category: "tool" },
  { id: "ms-teams", label: "Microsoft Teams", category: "tool", aliases: ["MS Teams"] },
  { id: "notion", label: "Notion", category: "tool", caseSensitive: true },
  { id: "linear", label: "Linear", category: "tool", caseSensitive: true },
  { id: "asana", label: "Asana", category: "tool" },
  { id: "trello", label: "Trello", category: "tool" },
  { id: "monday", label: "Monday.com", category: "tool" },
  { id: "miro", label: "Miro", category: "tool" },
  { id: "mural", label: "Mural", category: "tool" },
  { id: "figma", label: "Figma", category: "tool" },
  { id: "sketch", label: "Sketch", category: "tool" },
  { id: "xd", label: "Adobe XD", category: "tool" },
  { id: "invision", label: "InVision", category: "tool" },
  { id: "storybook", label: "Storybook", category: "tool" },
  { id: "webpack", label: "Webpack", category: "tool" },
  { id: "vite", label: "Vite", category: "tool" },
  { id: "rollup", label: "Rollup", category: "tool" },
  { id: "parcel", label: "Parcel", category: "tool" },
  { id: "esbuild", label: "esbuild", category: "tool" },
  { id: "swc", label: "SWC", category: "tool" },
  { id: "babel", label: "Babel", category: "tool" },
  { id: "turbopack", label: "Turbopack", category: "tool" },
  { id: "eslint", label: "ESLint", category: "tool" },
  { id: "prettier", label: "Prettier", category: "tool" },
  { id: "biome", label: "Biome", category: "tool" },
  { id: "jest", label: "Jest", category: "tool" },
  { id: "vitest", label: "Vitest", category: "tool" },
  { id: "mocha", label: "Mocha", category: "tool" },
  { id: "cypress", label: "Cypress", category: "tool" },
  { id: "playwright", label: "Playwright", category: "tool" },
  { id: "selenium", label: "Selenium", category: "tool" },
  { id: "puppeteer", label: "Puppeteer", category: "tool" },
  { id: "junit", label: "JUnit", category: "tool" },
  { id: "testng", label: "TestNG", category: "tool" },
  { id: "pytest", label: "pytest", category: "tool" },
  { id: "rspec", label: "RSpec", category: "tool" },
  { id: "postman", label: "Postman", category: "tool" },
  { id: "insomnia", label: "Insomnia", category: "tool" },
  { id: "datadog", label: "Datadog", category: "tool" },
  { id: "newrelic", label: "New Relic", category: "tool" },
  { id: "grafana", label: "Grafana", category: "tool" },
  { id: "prometheus", label: "Prometheus", category: "tool" },
  { id: "sentry", label: "Sentry", category: "tool" },
  { id: "splunk", label: "Splunk", category: "tool" },
  { id: "elk", label: "ELK Stack", category: "tool", aliases: ["Elastic Stack"] },
  { id: "kibana", label: "Kibana", category: "tool" },
  { id: "logstash", label: "Logstash", category: "tool" },
  { id: "mixpanel", label: "Mixpanel", category: "tool" },
  { id: "amplitude", label: "Amplitude", category: "tool" },
  { id: "segment", label: "Segment", category: "tool" },
  { id: "ga", label: "Google Analytics", category: "tool", aliases: ["GA4"] },
  { id: "stripe", label: "Stripe", category: "tool" },
  { id: "paypal", label: "PayPal", category: "tool" },
  { id: "twilio", label: "Twilio", category: "tool" },
  { id: "sendgrid", label: "SendGrid", category: "tool" },
  { id: "auth0", label: "Auth0", category: "tool" },
  { id: "okta", label: "Okta", category: "tool" },
  { id: "keycloak", label: "Keycloak", category: "tool" },
  { id: "snyk", label: "Snyk", category: "tool" },
  { id: "sonarqube", label: "SonarQube", category: "tool" },
  { id: "nexus", label: "Sonatype Nexus", category: "tool", aliases: ["Nexus Repository"] },
  { id: "artifactory", label: "JFrog Artifactory", category: "tool", aliases: ["Artifactory"] },
  { id: "vscode", label: "VS Code", category: "tool", aliases: ["Visual Studio Code"] },
  { id: "intellij", label: "IntelliJ IDEA", category: "tool", aliases: ["IntelliJ"] },
  { id: "eclipse", label: "Eclipse IDE", category: "tool", aliases: ["Eclipse"] },
  { id: "vs", label: "Visual Studio", category: "tool" },
  { id: "xcode", label: "Xcode", category: "tool" },
  { id: "android-studio", label: "Android Studio", category: "tool" },
  { id: "sap-gui", label: "SAP GUI", category: "tool", aliases: ["SAPGUI"] },
  { id: "sap-adt", label: "ABAP Development Tools", category: "tool", aliases: ["ADT", "ABAP in Eclipse"] },
  { id: "sap-fiori", label: "SAP Fiori", category: "tool" },
  { id: "sap-ui5", label: "SAPUI5", category: "tool", aliases: ["UI5"] },
  { id: "salesforce", label: "Salesforce", category: "tool" },
  { id: "servicenow", label: "ServiceNow", category: "tool" },
  { id: "tableau", label: "Tableau", category: "tool" },
  { id: "powerbi", label: "Power BI", category: "tool", aliases: ["PowerBI", "Microsoft Power BI"] },
  { id: "qlik", label: "Qlik", category: "tool", aliases: ["QlikView", "Qlik Sense"] },
  { id: "looker", label: "Looker", category: "tool" },
  { id: "metabase", label: "Metabase", category: "tool" },
  { id: "excel", label: "Microsoft Excel", category: "tool", aliases: ["Excel"], caseSensitive: true },
  { id: "office365", label: "Microsoft 365", category: "tool", aliases: ["Office 365", "MS Office"] },
  { id: "sharepoint", label: "SharePoint", category: "tool" },
  { id: "dynamics365", label: "Dynamics 365", category: "tool", aliases: ["MS Dynamics", "Dynamics 365 CRM"] },
  { id: "sap-erp", label: "SAP ERP", category: "tool", aliases: ["SAP ECC", "SAP S/4HANA", "S/4HANA", "S4HANA"] },
  { id: "sap-fi", label: "SAP FI", category: "tool", aliases: ["SAP Finance"] },
  { id: "sap-co", label: "SAP CO", category: "tool", aliases: ["SAP Controlling"] },
  { id: "sap-mm", label: "SAP MM", category: "tool" },
  { id: "sap-sd", label: "SAP SD", category: "tool" },
  { id: "sap-trm", label: "SAP TRM", category: "tool", aliases: ["SAP Treasury", "Treasury and Risk Management"] },
  { id: "sap-bw", label: "SAP BW", category: "tool", aliases: ["SAP Business Warehouse", "BW/4HANA"] },

  // ───────── Methodologies / Standards ─────────
  { id: "agile", label: "Agile", category: "methodology" },
  { id: "scrum", label: "Scrum", category: "methodology" },
  { id: "kanban", label: "Kanban", category: "methodology" },
  { id: "lean", label: "Lean", category: "methodology", matchTerms: ["Lean Management", "Lean"], caseSensitive: true },
  { id: "xp", label: "Extreme Programming", category: "methodology", aliases: ["XP"] },
  { id: "safe", label: "SAFe", category: "methodology", matchTerms: ["Scaled Agile Framework", "SAFe"], caseSensitive: true },
  { id: "less-framework", label: "LeSS", category: "methodology", aliases: ["Large-Scale Scrum"] },
  { id: "waterfall", label: "Wasserfall", category: "methodology", aliases: ["Waterfall"] },
  { id: "devops", label: "DevOps", category: "methodology" },
  { id: "devsecops", label: "DevSecOps", category: "methodology" },
  { id: "gitops", label: "GitOps", category: "methodology" },
  { id: "cicd", label: "CI/CD", category: "methodology", aliases: ["Continuous Integration", "Continuous Delivery", "Continuous Deployment"] },
  { id: "tdd", label: "Test-Driven Development", category: "methodology", aliases: ["TDD"] },
  { id: "bdd", label: "Behavior-Driven Development", category: "methodology", aliases: ["BDD"] },
  { id: "ddd", label: "Domain-Driven Design", category: "methodology", aliases: ["DDD"] },
  { id: "clean-arch", label: "Clean Architecture", category: "methodology" },
  { id: "hex-arch", label: "Hexagonal Architecture", category: "methodology", aliases: ["Ports and Adapters"] },
  { id: "microservices", label: "Microservices", category: "methodology", aliases: ["Mikroservices"] },
  { id: "event-driven", label: "Event-Driven Architecture", category: "methodology", aliases: ["EDA"] },
  { id: "soa", label: "SOA", category: "methodology", aliases: ["Service-Oriented Architecture"] },
  { id: "mvc", label: "MVC", category: "methodology", aliases: ["Model-View-Controller"] },
  { id: "mvvm", label: "MVVM", category: "methodology" },
  { id: "rest", label: "REST", category: "methodology", matchTerms: ["RESTful API", "RESTful", "REST API", "REST"], caseSensitive: true },
  { id: "grpc", label: "gRPC", category: "methodology" },
  { id: "soap", label: "SOAP", category: "methodology", caseSensitive: true },
  { id: "websocket", label: "WebSocket", category: "methodology", aliases: ["WebSockets"] },
  { id: "oauth", label: "OAuth 2.0", category: "methodology", aliases: ["OAuth", "OAuth2"] },
  { id: "jwt", label: "JWT", category: "methodology", aliases: ["JSON Web Token"] },
  { id: "saml", label: "SAML", category: "methodology" },
  { id: "openid", label: "OpenID Connect", category: "methodology", aliases: ["OIDC"] },
  { id: "owasp", label: "OWASP Top 10", category: "methodology", aliases: ["OWASP"] },
  { id: "iso27001", label: "ISO 27001", category: "methodology" },
  { id: "iso9001", label: "ISO 9001", category: "methodology" },
  { id: "gdpr", label: "DSGVO", category: "methodology", aliases: ["GDPR", "Datenschutzgrundverordnung"] },
  { id: "soc2", label: "SOC 2", category: "methodology" },
  { id: "pcidss", label: "PCI-DSS", category: "methodology", aliases: ["PCI DSS"] },
  { id: "hipaa", label: "HIPAA", category: "methodology" },
  { id: "itil", label: "ITIL", category: "methodology" },
  { id: "prince2", label: "PRINCE2", category: "methodology" },
  { id: "pmi", label: "PMI", category: "methodology" },
  { id: "pmp", label: "PMP", category: "methodology" },
  { id: "ipma", label: "IPMA", category: "methodology" },
  { id: "uml", label: "UML", category: "methodology" },
  { id: "bpmn", label: "BPMN", category: "methodology" },
  { id: "togaf", label: "TOGAF", category: "methodology" },

  // ───────── Languages spoken ─────────
  { id: "lang-de", label: "Deutsch", category: "language", aliases: ["German", "Muttersprache Deutsch"] },
  { id: "lang-en", label: "Englisch", category: "language", aliases: ["English", "Business English"] },
  { id: "lang-fr", label: "Französisch", category: "language", aliases: ["French", "Francais", "Français"] },
  { id: "lang-es", label: "Spanisch", category: "language", aliases: ["Spanish", "Español"] },
  { id: "lang-it", label: "Italienisch", category: "language", aliases: ["Italian", "Italiano"] },
  { id: "lang-pt", label: "Portugiesisch", category: "language", aliases: ["Portuguese", "Português"] },
  { id: "lang-nl", label: "Niederländisch", category: "language", aliases: ["Dutch", "Nederlands"] },
  { id: "lang-ru", label: "Russisch", category: "language", aliases: ["Russian"] },
  { id: "lang-zh", label: "Chinesisch", category: "language", aliases: ["Chinese", "Mandarin"] },
  { id: "lang-ja", label: "Japanisch", category: "language", aliases: ["Japanese"] },
  { id: "lang-pl", label: "Polnisch", category: "language", aliases: ["Polish"] },
  { id: "lang-tr", label: "Türkisch", category: "language", aliases: ["Turkish"] },
  { id: "lang-ar", label: "Arabisch", category: "language", aliases: ["Arabic"] },

  // ───────── Soft Skills ─────────
  { id: "ss-communication", label: "Kommunikationsstärke", category: "soft-skill", aliases: ["Kommunikationsfähigkeit", "Kommunikationskompetenz", "Communication Skills"] },
  { id: "ss-teamwork", label: "Teamfähigkeit", category: "soft-skill", aliases: ["Teamplayer", "Teamgeist", "Team Player"] },
  { id: "ss-leadership", label: "Führungskompetenz", category: "soft-skill", aliases: ["Leadership", "Führungserfahrung", "Führungsstärke", "People Leadership"] },
  { id: "ss-pm", label: "Projektmanagement", category: "soft-skill", aliases: ["Project Management"] },
  { id: "ss-ownership", label: "Eigeninitiative", category: "soft-skill", aliases: ["Ownership", "Selbstständigkeit", "Selbständigkeit"] },
  { id: "ss-responsibility", label: "Verantwortungsbewusstsein", category: "soft-skill" },
  { id: "ss-analytical", label: "Analytisches Denken", category: "soft-skill", aliases: ["Analytical Thinking", "analytische Fähigkeiten"] },
  { id: "ss-problemsolving", label: "Problemlösungskompetenz", category: "soft-skill", aliases: ["Problem Solving", "lösungsorientiert", "lösungsorientiertes Arbeiten"] },
  { id: "ss-resilience", label: "Belastbarkeit", category: "soft-skill", aliases: ["Resilienz", "Resilience"] },
  { id: "ss-flexibility", label: "Flexibilität", category: "soft-skill", aliases: ["Flexibility"] },
  { id: "ss-creativity", label: "Kreativität", category: "soft-skill", aliases: ["Creativity"] },
  { id: "ss-detail", label: "Detailorientierung", category: "soft-skill", aliases: ["Detail-orientiert", "Sorgfalt"] },
  { id: "ss-timemgmt", label: "Zeitmanagement", category: "soft-skill", aliases: ["Time Management"] },
  { id: "ss-presentation", label: "Präsentationsfähigkeiten", category: "soft-skill", aliases: ["Präsentationskompetenz", "Presentation Skills"] },
  { id: "ss-negotiation", label: "Verhandlungsgeschick", category: "soft-skill", aliases: ["Verhandlungskompetenz", "Negotiation Skills"] },
  { id: "ss-empathy", label: "Empathie", category: "soft-skill", aliases: ["Empathy"] },
  { id: "ss-conflict", label: "Konfliktfähigkeit", category: "soft-skill", aliases: ["Conflict Resolution"] },
  { id: "ss-intercultural", label: "Interkulturelle Kompetenz", category: "soft-skill", aliases: ["Intercultural Competence"] },
  { id: "ss-customer", label: "Kundenorientierung", category: "soft-skill", aliases: ["Customer Focus", "Customer Orientation"] },
  { id: "ss-strategic", label: "Strategisches Denken", category: "soft-skill", aliases: ["Strategic Thinking"] },
  { id: "ss-mentoring", label: "Mentoring", category: "soft-skill", aliases: ["Coaching"] },
  { id: "ss-stakeholder", label: "Stakeholder Management", category: "soft-skill" },
];

export interface SkillTerm {
  skill: Skill;
  term: string;
  caseSensitive: boolean;
}

function buildTerms(taxonomy: Skill[]): SkillTerm[] {
  const out: SkillTerm[] = [];
  for (const s of taxonomy) {
    const terms = s.matchTerms ?? [s.label, ...(s.aliases ?? [])];
    for (const t of terms) {
      if (t && t.trim()) {
        out.push({ skill: s, term: t.trim(), caseSensitive: !!s.caseSensitive });
      }
    }
  }
  // Longest term first so "Spring Boot" claims the span before "Spring".
  out.sort((a, b) => b.term.length - a.term.length);
  return out;
}

// The active taxonomy is what extraction/display read. It starts as the
// built-in set and can be replaced at runtime by the user's customizing.
let activeTaxonomy: Skill[] = BUILTIN_TAXONOMY;
let activeTerms: SkillTerm[] = buildTerms(BUILTIN_TAXONOMY);
let activeById = new Map<string, Skill>(BUILTIN_TAXONOMY.map((s) => [s.id, s]));

export function setActiveTaxonomy(taxonomy: Skill[]): void {
  activeTaxonomy = taxonomy;
  activeTerms = buildTerms(taxonomy);
  activeById = new Map(taxonomy.map((s) => [s.id, s]));
}

export function getActiveTaxonomy(): Skill[] {
  return activeTaxonomy;
}

export function allSkillTerms(): SkillTerm[] {
  return activeTerms;
}

export function skillById(id: string): Skill | undefined {
  return activeById.get(id);
}
